version: '3'

services:
  nginx:
    image: nginx:alpine
    ports:
      - ${IP}:${PORT}:80 # change ip if required
    volumes:
      - ./src/wp:/var/www/html
      - ./src/adminer.php:/var/www/html/adminer.php
      - ./config/server.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - wp
  wp:
    image: wordpress:fpm-alpine # https://hub.docker.com/_/wordpress/
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./src/wp:/var/www/html
      - ./src/adminer.php:/var/www/html/adminer.php
      #- ./src/plugins/plugin-name/:/var/www/html/wp-content/plugins/plugin-name # Plugin development
      #- ./src/themes/theme-name/:/var/www/html/wp-content/themes/theme-name # Theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - db
  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./src/wp:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "${DB_ROOT_PASSWORD}"
    depends_on:
      - wp
    profiles:
      - cli
  db:
    image: mysql:8.0 # https://hub.docker.com/_/mysql/
    ports:
      - ${IP}:3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - ./wp-data:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"

